# Generated by Django 4.1.7 on 2023-05-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('idMovie', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('releaseDate', models.DateField()),
                ('imdbUrl', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(to='peliculas.category')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('zipCode', models.CharField(max_length=5)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.occupation')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('idMovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.movie')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.user')),
            ],
        ),
    ]
