# Generated by Django 4.1.7 on 2023-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_rating_timestamp_alter_category_idcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releaseDate',
            field=models.DateField(null=True),
        ),
    ]
